Задание 1. Ручное глобальное выравнивание

In [20]:
!pip install biopython matplotlib numpy -q

import numpy as np
from Bio import SeqIO, Entrez
import matplotlib.pyplot as plt
import urllib.request
import os


In [22]:


def needleman_wunsch(seq1, seq2, match=3, mismatch=-3, gap=-2):
    n, m = len(seq1), len(seq2)
    F = np.zeros((n+1, m+1), dtype=int)
    # инициализация
    for i in range(1, n+1):
        F[i,0] = F[i-1,0] + gap
    for j in range(1, m+1):
        F[0,j] = F[0,j-1] + gap
    # заполнение
    for i in range(1, n+1):
        for j in range(1, m+1):
            diag = F[i-1,j-1] + (match if seq1[i-1]==seq2[j-1] else mismatch)
            up   = F[i-1,j] + gap
            left = F[i,j-1] + gap
            F[i,j] = max(diag, up, left)
    score = F[n,m]
    # backtrack
    al1, al2 = [], []
    i, j = n, m
    while i > 0 or j > 0:
        if i>0 and j>0 and F[i,j] == F[i-1,j-1] + (match if seq1[i-1]==seq2[j-1] else mismatch):
            al1.append(seq1[i-1]); al2.append(seq2[j-1])
            i -= 1; j -= 1
        elif i>0 and F[i,j] == F[i-1,j] + gap:
            al1.append(seq1[i-1]); al2.append('-')
            i -= 1
        else:
            al1.append('-'); al2.append(seq2[j-1])
            j -= 1
    al1.reverse(); al2.reverse()
    return F, score, ''.join(al1), ''.join(al2)

X = "ATGCGG"
Y = "ATCG"
F_global, score_global, al1_global, al2_global = needleman_wunsch(X, Y)
print("Матрица F (глобальное выравнивание):")
print(F_global)
print(f"Score: {score_global}")
print("Выравнивание:")
print(al1_global)
print(al2_global)

Матрица F (глобальное выравнивание):
[[  0  -2  -4  -6  -8]
 [ -2   3   1  -1  -3]
 [ -4   1   6   4   2]
 [ -6  -1   4   3   7]
 [ -8  -3   2   7   5]
 [-10  -5   0   5  10]
 [-12  -7  -2   3   8]]
Score: 8
Выравнивание:
ATGCGG
AT-C-G
