Задание 1. Ручное локальное выравнивание

In [20]:
!pip install biopython matplotlib numpy -q

import numpy as np
from Bio import SeqIO, Entrez
import matplotlib.pyplot as plt
import urllib.request
import os


In [24]:


def smith_waterman(seq1, seq2, match=3, mismatch=-3, gap=-2):
    n, m = len(seq1), len(seq2)
    H = np.zeros((n+1, m+1), dtype=int)
    max_score = 0
    max_pos = (0,0)
    for i in range(1, n+1):
        for j in range(1, m+1):
            diag = H[i-1,j-1] + (match if seq1[i-1]==seq2[j-1] else mismatch)
            up   = H[i-1,j] + gap
            left = H[i,j-1] + gap
            H[i,j] = max(0, diag, up, left)
            if H[i,j] > max_score:
                max_score = H[i,j]
                max_pos = (i,j)
    score = max_score

    al1, al2 = [], []
    i, j = max_pos
    while H[i,j] > 0:
        if H[i,j] == H[i-1,j-1] + (match if seq1[i-1]==seq2[j-1] else mismatch):
            al1.append(seq1[i-1]); al2.append(seq2[j-1])
            i -= 1; j -= 1
        elif H[i,j] == H[i-1,j] + gap:
            al1.append(seq1[i-1]); al2.append('-')
            i -= 1
        else:
            al1.append('-'); al2.append(seq2[j-1])
            j -= 1
    al1.reverse(); al2.reverse()
    return H, score, ''.join(al1), ''.join(al2)

H_local, score_local, al1_local, al2_local = smith_waterman(X, Y)
print("Матрица H (локальное выравнивание):")
print(H_local)
print(f"Score: {score_local}")
print("Выравнивание:")
print(al1_local)
print(al2_local)

Матрица H (локальное выравнивание):
[[ 0  0  0  0  0]
 [ 0  3  1  0  0]
 [ 0  1  6  4  2]
 [ 0  0  4  3  7]
 [ 0  0  2  7  5]
 [ 0  0  0  5 10]
 [ 0  0  0  3  8]]
Score: 10
Выравнивание:
ATGCG
AT-CG
